FORMAT: 1A

# CatchupTV APIs
List of all catchup TV APIs
NOTE: test phase

## Epg DB [/epg]
### Retrieve a EPG Data [GET]
+ Parameters
    + programstart: "gte.1000000000" (required)

+ Response 200 

## Trim DB [/trim]
### Retrieve Trims data [GET]
+ Response 200 

## Trim Jobs [/trim-jobs]
### Do Trims jobs [GET]
+ Response 200 

## Offline play [/offline-play]
### HLS playlist/content in offline mode [GET]
+ Response 200 

## Live play [/live-play]
### HLS playlist/content in Live mode [GET]
+ Response 200 



