apiVersion: v1
kind: Service
metadata:
  name: cs-db-epg-api
  labels:
    app: cs-db-epg-api
    topic: epg
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: cs-db-epg-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-db-epg-api-dep
  labels:
    tire: core
    topic: epg
spec:
  selector:
    matchLabels:
      app: cs-db-epg-api
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-db-epg-api
        topic: epg
    spec:
      containers:
        - name: cs-db-epg-api
          image: postgrest/postgrest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cs-db-info-config
