apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-db-trim-api-config
data:
  PGRST_DB_URI: "postgres://postgres:31233123@cs-db-trim:5432/postgres"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: cs-db-trim-api
  labels:
    app: cs-db-trim-api
    topic: trim
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: cs-db-trim-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-db-trim-api-dep
  labels:
    tire: core
    topic: trim
spec:
  selector:
    matchLabels:
      app: cs-db-trim-api
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-db-trim-api
        topic: trim
    spec:
      containers:
        - name: cs-db-trim-api
          image: postgrest/postgrest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cs-db-trim-api-config
