apiVersion: batch/v1
kind: Job
metadata:
  name: cs-file-to-hls-hash
spec:
  template:
    spec:
      containers:
        - name: cs-file-to-hls-hash
          image: busybox:1.28
          
          command: ['sh', '-c', "sleep 10"]
      restartPolicy: Never
