apiVersion: v1
kind: Service
metadata:
  name: cs-input-deploy
  labels:
    app: cs-input-deploy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: cs-input-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-input-deploy-dep
  labels:
    tire: core
    topic: info
spec:
  selector:
    matchLabels:
      app: cs-input-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-input-deploy
    spec:
      containers:
        - name: cs-input-deploy
          image: cs-input-deploy
          
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cs-db-info-config
