apiVersion: batch/v1
kind: Job
metadata:
  name: cs-live-to-hls-dep-2
  labels:
    tire: channel
    topic: hls
spec:
  template:
    metadata:
      labels:
        app: cs-live-to-hls-2
        topic: hls
    spec:
      volumes:
        - name: hls-out
          emptyDir:
            medium: "Memory"

      restartPolicy: Never
      containers:
        - name: cs-live-to-hls
          image: cs-file-to-hls
          imagePullPolicy: Never
          volumeMounts:
            - name: hls-out
              mountPath: /hls
          envFrom:
            - configMapRef:
                name: cs-gb-mq-config
