apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-live-to-hls-config-3
data:
  CHANNEL_NAME: "Other channel"
  CHANNEL_LIVE: "true"
  CHANNEL_DAILY_START: "00:00"
  CHANNEL_DAILY_STOP: "23:59"
  CHANNEL_URL: "https://tv.razavi.ir/hls/rozeh_1.m3u8"
  CHANNEL_BANDWIDTH: "1000000"
  HLS_VIDEO_CODEC: "copy"
  HLS_VIDEO_BITRATE: "2000k"
  HLS_VIDEO_SIZE: "1280x720"
  HLS_VIDEO_FPS: "25"
  HLS_AUDIO_CODEC: "copy"
  HLS_AUDIO_BITRATE: "128k"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-live-to-hls-dep-3
  labels:
    tire: channel
    topic: hls
spec:
  selector:
    matchLabels:
      app: cs-live-to-hls
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-live-to-hls
        topic: hls
    spec:
      volumes:
        - name: hls-out
          emptyDir:
            medium: "Memory"

      containers:
        - name: cs-live-to-hls
          image: cs-live-to-hls
          imagePullPolicy: Never
          volumeMounts:
            - name: hls-out
              mountPath: /hls
          envFrom:
            - configMapRef:
                name: cs-gb-config
            - configMapRef:
                name: cs-live-to-hls-config-3
      initContainers:
        - name: wait-for-mq
          image: busybox:1.28
          imagePullPolicy: Never
          command: ['sh', '-c', "until nslookup $GB_MQ_HOST; do echo \
'Wait for gb-mq'; sleep 3; done"]
          envFrom:
            - configMapRef:
                name: cs-gb-config
