apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-live-play-config
data:
  LIVE_CACHE_PASS: "31233123"
---
apiVersion: v1
kind: Service
metadata:
  name: cs-live-play
  labels:
    app: cs-live-play
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cs-live-play
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-live-play-dep
  labels:
    tire: core
    topic: live
spec:
  selector:
    matchLabels:
      app: cs-live-play
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-live-play
    spec:
      containers:
        - name: cs-live-play
          image: cs-live-play
          
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cs-gb-mq-config
            - configMapRef:
                name: cs-live-play-config
