apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-fs-db-cache-push-dep
  labels:
    tire: core
    topic: segment
spec:
  selector:
    matchLabels:
      app: cs-fs-db-cache-push
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-fs-db-cache-push
        topic: segment
    spec:
      containers:
        - name: cs-fs-db-cache-push
          image: cs-fs-db-cache-push
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: cs-db-seg-config
            - configMapRef:
                name: cs-live-cache-config
            - configMapRef:
                name: cs-gb-mq-config
          volumeMounts:
            - name: seg-data
              mountPath: /data
      volumes:
        - name: seg-data
          persistentVolumeClaim:
            claimName: cs-pvc-fs-seg
      initContainers:
        - name: wait-for-mq
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $CS_GB_MQ_SERVICE_HOST; \
                do echo 'Wait for gb-mq'; sleep 3; done"]
        - name: wait-for-live-mq
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $CS_LIVE_CACHE_SERVICE_HOST; \
                do echo 'Wait for live-mq'; sleep 3; done"]
