apiVersion: v1
kind: Service
metadata:
  name: cs-db-info-api
  labels:
    app: cs-db-info-api
    topic: info
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cs-db-info-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-db-info-api-dep
  labels:
    tire: core
    topic: info
spec:
  selector:
    matchLabels:
      app: cs-db-info-api
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-db-info-api
        topic: info
    spec:
      containers:
        - name: cs-db-info-api
          image: cs-db-info-api
          
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cs-db-info-config
