apiVersion: v1
kind: Service
metadata:
  name: cs-offline-play
  labels:
    app: cs-offline-play
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cs-offline-play
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-offline-play-dep
  labels:
    tire: core
    topic: live
spec:
  selector:
    matchLabels:
      app: cs-offline-play
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-offline-play
    spec:
      containers:
        - name: cs-offline-play
          image: cs-offline-play
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cs-db-info-config
            - configMapRef:
                name: cs-db-seg-config
          volumeMounts:
            - name: seg-data
              mountPath: /data
      volumes:
        - name: seg-data
          persistentVolumeClaim:
            claimName: cs-pvc-fs-seg
