apiVersion: v1
kind: ConfigMap
metadata:
  name: chan-net-to-epg-config
data:
  EPG_SOURCE_TYPE: "dvb"
  EPG_SOURCE_URL: "udp://224.2.2.2:2000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chan-net-to-epg-dep
  labels:
    tire: channel
    topic: epg
spec:
  selector:
    matchLabels:
      app: chan-net-to-epg
  replicas: 1
  template:
    metadata:
      labels:
        app: chan-net-to-epg
        topic: epg
    spec:
      containers:
        - name: chan-net-to-epg
          image: chan-net-to-epg
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: gb-config
            - configMapRef:
                name: chan-net-to-epg-config
