apiVersion: apps/v1
kind: Deployment
metadata:
  name: chan-net-to-epg-deployment
spec:
  selector:
    matchLabels:
      app: chan-net-to-epg
  replicas: 1
  template:
    metadata:
      labels:
        app: chan-net-to-epg
    spec:
      containers:
        - name: chan-net-to-epg
          image: localhost:32000/chan-net-to-epg:registry
          env:
            - name: GB_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-host
            - name: GB_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-user
            - name: GB_MQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-pass
            - name: GB_MQ_EPG_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-epg-queue
            - name: EPG_SOURCE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: epg-source-type
            - name: EPG_SOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: epg-source-url
