apiVersion: v1
kind: Service
metadata:
  name: db-epg
  labels:
    app: db-epg
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: db-epg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-epg-deployment
spec:
  selector:
    matchLabels:
      app: db-epg
  replicas: 1
  template:
    metadata:
      labels:
        app: db-epg
    spec:
      containers:
        - name: db-epg
          image: localhost:32000/db-epg:registry
          ports:
            - containerPort: 3000
          env:
            - name: GB_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-host
            - name: GB_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-user
            - name: GB_MQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-pass
            - name: GB_MQ_EPG_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-epg-queue
          volumeMounts:
            - mountPath: /data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}    # TODO: MUST BE PERSISTENT
