apiVersion: v1
kind: Service
metadata:
  name: db-segment
  labels:
    app: db-segment
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: db-segment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-segment-deployment
spec:
  selector:
    matchLabels:
      app: db-segment
  replicas: 1
  template:
    metadata:
      labels:
        app: db-segment
    spec:
      containers:
        - name: db-segment
          image: localhost:32000/db-segment:registry
          ports:
            - containerPort: 3000
          env:
            - name: GB_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-host
            - name: GB_MQ_USER
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-user
            - name: GB_MQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-pass
            - name: GB_MQ_SEG_INFO_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: gb-config
                  key: gb-mq-seg-info-queue
