apiVersion: v1
kind: Service
metadata:
  name: db-segment
  labels:
    app: db-segment
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: db-segment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-segment-deployment
spec:
  selector:
    matchLabels:
      app: db-segment
  replicas: 1
  template:
    metadata:
      labels:
        app: db-segment
    spec:
      containers:
        - name: db-segment
          image: db-segment
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: gb-config
          volumeMounts:
            - mountPath: /data
              name: db-data
      volumes:
        - name: db-data
          emptyDir: {}    # TODO: MUST BE PERSISTENT
