apiVersion: v1
kind: ConfigMap
metadata:
  name: fs-segment-config
data:
  GB_MQ_HOST: "gb-mq"
  # TODO: MOVE  TO SECRET
  GB_MQ_USER: "karim"
  GB_MQ_PASS: "31233123"
  GB_MQ_SEQ_DATA_QUEUE: "seg_data"

---
apiVersion: v1
kind: Service
metadata:
  name: fs-segment-nginx
  labels:
    app: fs-segment-nginx
    topic: segment
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fs-segment-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-segment-nginx-dep
  labels:
    tire: core
    topic: segment
spec:
  selector:
    matchLabels:
      app: fs-segment-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: fs-segment-nginx
        topic: segment
    spec:
      containers:
        - name: fs-segment-nginx
          image: nginx:1.19
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: seg-data
              mountPath: /var/www/html/seg
      volumes:
        - name: seg-data
          persistentVolumeClaim:
            claimName: pvc-fs-segment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-segment-insert-dep
  labels:
    tire: core
    topic: segment
spec:
  selector:
    matchLabels:
      app: fs-segment-insert
  replicas: 1
  template:
    metadata:
      labels:
        app: fs-segment-insert
        topic: segment
    spec:
      containers:
        - name: fs-segment-insert
          image: fs-insert
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: fs-segment-config
          volumeMounts:
            - name: seg-data
              mountPath: /seg
      volumes:
        - name: seg-data
          persistentVolumeClaim:
            claimName: pvc-fs-segment
