apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-net-stream-deployment
spec:
  selector:
    matchLabels:
      app: test-net-stream
  replicas: 1
  template:
    metadata:
      labels:
        app: test-net-stream
    spec:
#      securityContext:
#        runAsUser: 0
#        runAsGroup: 0
      volumes:
        - name: seg-data
          persistentVolumeClaim:
            claimName: pvc-fs-segment
      containers:
        - name: test-net-stream
          image: test-net-stream
          imagePullPolicy: Never
          volumeMounts:
            - name: seg-data
              mountPath: /test_data
          envFrom:
            - configMapRef:
                name: gb-config
