apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-live-to-hls-dep
  labels:
    tire: channel
    topic: hls
spec:
  selector:
    matchLabels:
      app: cs-live-to-hls
  replicas: 1
  template:
    metadata:
      labels:
        app: cs-live-to-hls
        topic: hls
    spec:
      volumes:
        - name: hls-out
          emptyDir:
            medium: "Memory"
      containers:
        - name: cs-live-to-hls
          image: cs-live-to-hls
          imagePullPolicy: Never
          volumeMounts:
            - name: hls-out
              mountPath: /hls
          envFrom:
            - configMapRef:
                name: cs-gb-mq-config
      initContainers:
        - name: wait-for-mq
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $CS_GB_MQ_SERVICE_HOST; do echo \
'Wait for gb-mq'; sleep 3; done"]
          envFrom:
            - configMapRef:
                name: cs-gb-mq-config
